### PR TITLE
XALANJ-2671: Restore history from `xalan-j_2_7_1_maint` into `master`

### PR DESCRIPTION
**Pull request by stanio**
The important thing is to have `xalan-j_2_7_1_maint` as the 1st parent of the merge.  The `master` branch should be then fast-forwarded to this merge.  Unless someone pushes more stuff onto `master` beforehand – the operation should be redone then:

```
git checkout -b xalanj-2671-restore-history origin/xalan-j_2_7_1_maint
git merge -X theirs origin/master
```

All changes from `master` are preserved/accepted _as is_ – there should be no content differences with `master`:

[`master..xalanj-2671-restore-history`](https://github.com/apache/xalan-java/compare/master..stanio:xalan-java:xalanj-2671-restore-history)

_Note,_ this PR should not be merged from Github's web UI.  Fetch `xalanj-2671-restore-history` from my fork, then:

```
git remote add stanio https://github.com/stanio/xalan-java.git
git fetch --all
git checkout master
git pull
git merge --ff-only stanio/xalanj-2671-restore-history
git push
```

Assuming the default remote is the original `xalan-java` repo.  This pull request should get automatically marked as merged, then.

Ref: [XALANJ-2671]

[XALANJ-2671]: https://issues.apache.org/jira/browse/XALANJ-2671 'Source code history lost in "clearing all contents" + "updating master branch, to have same contents as..." commits'

### CODE REVIEW

**Comment by stanio** [comment]
See the `DocumentCall.java` blame:

-   https://github.com/stanio/xalan-java/blame/xalanj-2671-restore-history/src/org/apache/xalan/xsltc/compiler/DocumentCall.java

**Comment by stanio** [comment]
> When I try to perform the above operations (including the first box), the git merge tells me...

The first box shows how this PR has been prepared.  The second box shows how it should be executed using my fork/branch being the source of this PR.  Thus you don't need the first box if you're going to use my branch, but then (_on Jul 1_):

> Unless someone pushes more stuff onto `master` beforehand – the operation should be redone then:
> ...
>
> All changes from `master` are preserved/accepted _as is_ – there should be no content differences with `master`:
> 
> [`master..xalanj-2671-restore-history`](https://github.com/apache/xalan-java/compare/master..stanio:xalan-java:xalanj-2671-restore-history)

If you follow the link you may see changes in `master` already.  Here are the added commits (changes shown in reverse):

-   [`xalanj-2671-restore-history...master`](https://github.com/stanio/xalan-java/compare/xalanj-2671-restore-history...apache:xalan-java:master)

I'll update this PR with a redone merge one more time.

**Comment by vlsi** [comment]
I suggest removing the bad commits rather than cluttering the history

**Comment by jkesselm** [comment]
On 10/16/2023 11:53 AM, Vladimir Sitnikov wrote:
> I suggest removing the bad commits rather than cluttering the history

Seems reasonable. I'm not sure I have the Git-fu to do it...

**Comment by stanio** [comment]
> I suggest removing the bad commits rather than cluttering the history

I can't do that in a PR, and only maintainers with (force) push rights to the main repo could do it.

> Seems reasonable. I'm not sure I have the Git-fu to do it...

That's why I'm suggesting this easier (as I've prepared half of it) and safer approach.  It still needs a maintainer with (just) push rights to the main repo.

**Comment by jkesselm** [comment]
OK; that fast-forwarded successfully.

**Comment by vlsi** [comment]
>I can't do that in a PR, and only maintainers with (force) push rights to the main repo could do it.

Of course

>That's why I'm suggesting this easier

I suggest:
1) prepare branch that removes bad commits
2) force push to the repo

It would produce much better history, and there’s nothing unsafe with that.

**Comment by stanio** [comment]
I've updated this PR with the current `master` changes:

> _Note,_ this PR should not be merged from Github's web UI. Fetch `xalanj-2671-restore-history` from my fork, then:
> 
> ```
> git remote add stanio https://github.com/stanio/xalan-java.git
> git fetch --all
> git checkout master
> git pull
> git merge --ff-only stanio/xalanj-2671-restore-history
> git push
> ```

One may try all but the last command.  Before pushing verify, for example:

```
$ git blame src/org/apache/xalan/xsltc/compiler/DocumentCall.java
02ac9a317b (Scott Boag                2001-04-17 18:52:52 +0000   1) /*
ef62e073fa (Brian James Minchau       2006-10-28 07:03:30 +0000   2)  * Licensed to the Apache Software Foundation (ASF) under one
...
```

There should be different authors listed and not just Mukul Gandhi as currently:

-   [DocumentCall.java](https://github.com/apache/xalan-java/blame/92781cb4c/src/org/apache/xalan/xsltc/compiler/DocumentCall.java)

**Comment by stanio** [comment]
See also #103.

**Comment by jkesselm** [comment]
Executed. Elegance be darned; it works.

**Comment by vlsi** [comment]
I suggest reverting this and following https://github.com/apache/xalan-java/pull/103 instead.

There's no point in cluttering the history by commits like https://github.com/apache/xalan-java/commit/9332320096328ab4f9b25d60d5154cfcdd6703e9, and it would definitely worsen the life of those who analyze xalan code when analyzing defects.

**Comment by jkesselm** [comment]
@stanio : Clarification, please: Are you agreeing that I should revert this and apply 103 instead (or first), or saying that 103 can still be applied?

**Comment by stanio** [comment]
If #103 would be applied, this one doesn't need a revert.  #103 resets the state from a different branch where this merge isn't present.  Reverting these changes by means of applying a reverse commit after the merge doesn't make sense here, nor does resetting the branch to the previous HEAD do any good, in my opinion.  #103 could still be applied as is currently.

**Comment by vlsi** [comment]
Adding to stanio explanation, there was no sense in merging this PR either as it would be discarded anyway when applying 103.

**Pull request merged**
