### PR TITLE
committing enhancements to xs:dateTime data type's implementation, and adding few new working test cases for xs:dateTime data type's arithmetic. also modifying the NOTICE.txt file, mentioning details of few implementation dependencies for this xalanj dev repos branch.

### PR DESCRIPTION
**Pull request by mukulga**

### CODE REVIEW

**Comment by vlsi** [comment]
@mukulga , this PR brings "Eclipse Public License" source dependency which is forbidden by the ASF rules.

>https://www.apache.org/legal/resolved.html#binary-only-inclusion-condition
> Do not include Category B licensed works in source releases.

---

@mukulga , could you please stop creating immediately closing PRs?

Creating a PR like that adds no value, and it does clutter "pull requests" tab on GitHub.

Please use concise wording. The title of the current PR is "committing enhancements to xs:dateTime data type's implementation, and adding a few new working test cases for xs:dateTime data type's arithmetic. also modifying the NOTICE.txt file, mentioning details of a few implementation dependencies for this xalanj dev repos branch." which is unreasonably long.
Please take your time to summarize the change in  50-100 characters.

For instance,
* Stop using "committing enhancements" words. They literally add no value since, well, you make a commitment. Why duplicate that by saying "committing"?
* Move non-important data to the body rather than putting everything into the subject. Compare it with email: you should not put the full message into the subject line, and you should keep the subject short, and then you elaborate in the body. The same goes with commit messages: you put a short summary in the subject line, then you add a blank line, and then you put everything else.
* "adding few new working test cases" -- it is absolutely not needed for the subject line. Of course you added tests. Why putting an emphasis on that?
* "mentioning details of few implementation dependencies for this xalanj dev repos branch" this does not belong to the subject line as well


If you struggle with identifying what could be the proper commit message, assume you format an email:

```
SUBJECT

BODY
```

Then format your commit message **in the same way**

```
COMMIT HEADLINE (the most important information, like SUBJECT in email)

BODY (details)
```

**Comment by mukulga** [comment]
@vlsi, Thanks for pointing to this issue. Here's what I think, as of now with respect to this topic,

As mentioned within the NOTICE.txt file that we've modified yesterday on XalanJ's dev repos branch xalan-j_xslt3.0, we're using little bit (I guess, appx 0.1% or even lesser) of codebase (we're not using exact copies of the code files, but we're using few algorithm outlines which is not very much practicle to provide in software binary form within this XalanJ work) from Eclipse WTP project's XPath 2.0 processor (ref, https://projects.eclipse.org/projects/webtools). Apache XercesJ (for the XML Schema 1.1 version) also includes, Eclipse WTP project's XPath 2.0 processor jar file. The XercesJ team (including me :)), wrote many codebase improvements (we did not modify the core design or codebase of WTP's XPath 2.0 processor, but we solved various bugs bringing this XPath 2.0 processor's W3C XPath 2.0 test suite's compliance from appx 40% to near 100%) for Eclipse WTP project's XPath 2.0 processor.

We hope to elaborate more, and to comply more correctly, with the portions of codebase from "Eclipse WTP project's XPath 2.0 processor" that we're using, before we'll make a public release of XalanJ's XSLT 3.0 and XPath 3.1 implementation work. For now, we need to use few of the Eclipse WTP XPath 2.0 processor's code algorithm patterns, to make progress on XalanJ's XSLT 3.0 and XPath 3.1 implementation development.

> could you please stop creating immediately closing PRs?

> Creating a PR like that adds no value, and it does clutter "pull requests" tab on GitHub.

As I wrote within another XalanJ discussion thread 2-3 days ago to your question, about this same topic, for our reasons of creating PRs and merging them early by me as in this case. IHMO, I'm a XalanJ committer and I may commit code and merge that myself however quickly (my intention is never to inconvenience anyone on this list with the contents and frequency of my PRs). Any other XalanJ committer or a pmc member, can raise any concerns and objections to the PRs and the git merges that I'm doing on these PRs, and then I shall be bound to accept those points.

Also any product like XalanJ, that's in a midst of these development activities these days, is bound to have significant mail traffic. This is due to the work that we're doing, and not because we wish to inconvenience anyone.

> Please use concise wording. The title of the current PR is ...

I think, the PRs titles that we're using, need to convey as much as possible the purpose of the PR. Shortening the PR title, of a complicated code change, and not mentioning needed details on PR title, shall make it difficult for users to start reviewing the code changes of the PR. Deciding on this, is again I feel, is a prerogative of the project committer. IMHO, the PRs functional code contribution or a bug fix is important, than the text of the PR title.

**Comment by vlsi** [comment]
> we need to use few of the Eclipse WTP XPath 2.0 processor's code algorithm patterns, to make progress on XalanJ's XSLT 3.0 and XPath 3.1 implementation development

See https://www.apache.org/legal/release-policy.html#licensing

> Every ASF release MUST comply with ASF licensing policy. This requirement is of utmost importance and an audit SHOULD be performed before any full release is created

Of course, no release with xslt3 has been made yet, however, once you spoil the codebase with bad-licensed code, it will be hard to reverse it.

> we're not using exact copies of the code files, but we're using few algorithm outlines 

I would suggest asking for a lawyer, however, borrowing "only algorithms" does not sound much different from "borrowing exact code".
For instance, if you analyze code written in C, and "reproduce it in Java in Xalan", you still borrow from a project, and it does not count that you "use a completely different language".

Of course, it is up to PMC to decide what they think is shippable, however, this case sounds fishy to me.
The branch does contain code with a doubtful license. It means the code will be hard to release, and delaying such an analysis till the release would make it even harder.

---

> IHMO, I'm a XalanJ committer and I may commit code and merge that myself however quickly

Mukul, I beg your pardon, but it does not clarify the reason **why** you keep creating the PRs. Of course, you can create branches, commits, and PRs. Why do you keep creating PRs for xslt3 though?

> Any other XalanJ committer or a pmc member, can raise any concerns and objections to the PRs and the git merges that I'm doing on these PRs, and then I shall be bound to accept those points

Correct me if I am wrong: does that mean you consider concerns from other committers and PMC only?

**Comment by mukulga** [comment]
@vlsi,
> why you keep creating the PRs. Of course, you can create branches, commits, and PRs. Why do you keep creating PRs for xslt3 though?

I don't intend to be the only contributor to XalanJ's XSLT 3.0 and XPath 3.1 efforts. I wish that, other people should also come forward, and contribute to XalanJ's XSLT 3.0 and XPath 3.1 implementations.

Any XalanJ non-committers technically need to create PRs and request those to be merged to any of XalanJ dev repos branches. Existing XalanJ XSLT 3.0 and XPath 3.1 contributors like me for now, raising a PR, helps to have a XalanJ process already setup as of now for non-committers to be able to make their codebase contributions to XalanJ.   

> Correct me if I am wrong: does that mean you consider concerns from other committers and PMC only?

Definitely not, please.

**Comment by vlsi** [comment]
> helps to have a XalanJ process already setup as of now for non-committers to be able to make their codebase contributions to XalanJ

Committers already have an infrastructure: they can commit to a branch directly.
If you commit directly, it is less actions for everybody:
* less commits: no "merge" commits in history
* less notification noise for everybody: no "pr created and immediately closed" notifications
* less work for committers: they can just commit code instead of "commit code + create PR + merge PR"
 
>Definitely not, please.

Could you please clarify why you deviate from the Git recommendation then?
https://git-scm.com/docs/git-commit#_discussion

> Git commit man page: It’s a good idea to begin the commit message with a single short (less than 50 character) line summarizing the change, followed by a **blank line** and then a more thorough description.

> mukulga: Shortening the PR title, of a complicated code change, and not mentioning needed details on PR title, shall make it difficult for users to start reviewing the code changes of the PR

Please read `git-commit#_discussion` carefully. I do not suggest removing details.
I suggest using "subject" and "body" better: put the most important bits into **subject**, and put details in **body**. They should be separated by a blank line as per Git conventions.

It is not something I invented. It is a generic Git recommendation.
Do you think you could format commit messages into the subject line and the body?

**Comment by mukulga** [comment]
@vlsi,
> Committers already have an infrastructure: they can commit to a branch directly.
> If you commit directly, it is less actions for everybody

I actually started this way only few months ago. i.e, I was committing to the XalanJ dev repos branch xalan-j_xslt3.0 directly. If I may recall correctly, you suggested few months ago, for XalanJ committer(s) to create their own fork of the XalanJ repos branch, and then raise a PR to get that merged to XalanJ repos branch. I found your suggestion ok then, and made the switch (which required me to change, few git things on my local) to that process suggested by you.

Now you're suggesting us, to follow the earlier process (i.e, committing to the XalanJ dev repos branch xalan-j_xslt3.0 directly). This is normally not convenient. It seems to me that, currently only *you* (with due respect) is having issues with these XalanJ development activities, and no one else is mentioning about these issues on XalanJ lists or github.

Your opinions are very important for us to, think, evaluate and adopt (please keep on writing them). But if XalanJ committer(s) disagree to a certain point, IMHO you should respect that and not feel bad in any way, and not 'pressure' us to adopt your points.

Since you write frequently about, XalanJ git and other processes (these are very important topics for any software development project), and XalanJ committers and pmc members sometimes have different opinions, to the points raised, I think it'd be useful to have a 'XalanJ development and maintenance' process document kept on XalanJ repos. May be you should, or someone from XalanJ team may create a draft of this document, and then we may have a discussion and vote on XalanJ list to finalize that.

> I suggest using "subject" and "body" better: put the most important bits into **subject**, and put details in **body**

Thanks for this suggestion, and I find this useful and shall try to follow that.

**Pull request merged**
