### PR TITLE
Make sure serializer resources are included in JAR

### PR DESCRIPTION
**Pull request by kriegaex**
The resources were
1. in a non-standard directory → moved them,
2. not included in the Maven POM → included them.

I noticed while playing with the Brazil example, which was looking for one of the resource files and could not find it.

@kubycsolutions, this should be a quick and easy merge. Not worthy of its own Jira issue.

### CODE REVIEW

**Comment by kriegaex** [comment]
@jkesselm, rebased on _xalan-java-mvn-refactored_ after the latest PR merges.

**Review by jkesselm — APPROVED** [review]

**Comment by kriegaex** [comment]
@jkesselm, thanks for the review approval. Is anything stopping you from merging?

**Comment by jkesselm** [comment]
Not that I know of. It's 8PM here, so I may not get to it until tomorrow.

**Comment by kubycsolutions** [comment]
Oh. Already merged. Sorry. Android threw a four-day-old message at me.

I've added CI to my branch. It's unhappy; something about the reconstructed lib/ isn't being found correctly by test. Probably over-specific jarfile references, or something of that sort. Working the problem in test.

--
   /_  Joe Kesselman (he/him/his)
-/ _) My Alexa skill for New Music/New Sounds fans:
   /   https://www.amazon.com/dp/B09WJ3H657/

Caveat: Opinionated old geezer with overcompensated writer's block. May be redundant, verbose, prolix, sesquipedalian, didactic, officious, or redundant.
________________________________

**Pull request merged**
