### PR TITLE
XALANJ-2671: Reset `master` to `xalan-j_2_7_1_maint`

### PR DESCRIPTION
**Pull request by stanio**
Alternative to #14, as @vlsi suggests reset `master` to `xalan-j_2_7_1_maint`.

> **Important**
> This PR _should **not**_ be merged from Github's web UI.

Here are the steps I've taken to prepare the source branch:

```
git checkout -b xalanj-2671-master-reset origin/xalan-j_2_7_1_maint
git cherry-pick -m 1 ff6743972a
git cherry-pick -m 1 356ce496fa..92781cb4ce
git cherry-pick --skip
git cherry-pick --skip
git rebase -i origin/xalan-j_2_7_1_maint
```

-   I've created a new branch (`xalanj-2671-master-reset`) off of the `xalan-j_2_7_1_maint` one
-   Cherry-picked later additions to the `master` branch: 222095d55ac8352fd08f8fa23869fcd58660cea8...92781cb4ce9f56bed3b3dea8f9000e33193b0512, excluding 0affa12bb12e45bf681a6e6a918d68884d7e1877 and 356ce496faa80d97ae8a8406e37f6bd994b39233
    -   Two superfluous merge commits were dropped (`git cherry-pick --skip`)
-   Edited the cherry-picked ff6743972a311e2c69423a8821600332937826c4:
    ```diff
    -If you believe you found a vulnerability in Apache HttpClient,
    +If you believe you found a vulnerability in Apache XalanJ,
    ```

## Execution

Before anything else, please archive the current state by saving a few tags:

```
git tag trunk-20230301 222095d55a -m "Trunk until 2023-03-01"
git tag master-20231017 origin/master -m "Master until 2023-10-17"
git push origin trunk-20230301 master-20231017
```

Using the prepared `xalanj-2671-master-reset` branch from my fork (visible in this PR), assuming you've cloned the official repo (`origin`):

```
git remote add stanio https://github.com/stanio/xalan-java.git
git fetch --all
git checkout master
git reset --hard stanio/xalanj-2671-master-reset
```

Perform whatever sanity checks you can come up with, like looking at the resulting history graph, file blame annotations, etc.  When you're ready:

```
git push --force-with-lease
```

> **Note**
> Development branches created off of `master` after 2023-03-01 need to be rebased, after this.

### CODE REVIEW

**Comment by stanio** [comment]
* https://github.com/apache/xalan-java/compare/master..stanio:xalan-java:xalanj-2671-master-reset?w=1

There's some header info I'm missing from `SECURITY.md`.  Let me see... I think I need to do these separately:

```
git cherry-pick -m 1 ff6743972a
git cherry-pick -m 1 356ce496fa..92781cb4ce
```

**Comment by stanio** [comment]
🤪

```diff
$ git diff -w master..stanio/xalanj-2671-master-reset
diff --git a/SECURITY.md b/SECURITY.md
index cdf53d2f2..ec123bd5f 100644
--- a/SECURITY.md
+++ b/SECURITY.md
@@ -19,5 +19,5 @@

 # Reporting a vulnerability

-If you believe you found a vulnerability in Apache XalanJ,
+If you believe you found a vulnerability in Apache HttpClient,
 please contact [the Apache Security Team](https://www.apache.org/security/).
```

This appears to have been "silently" corrected in 356ce496faa80d97ae8a8406e37f6bd994b39233.

**Comment by stanio** [comment]
@vlsi, please verify if this solution satisfies your requirements for a clean history.

@jkesselm and the xalan-java team, please apply your best scrutiny on this PR.

**Comment by stanio** [comment]
> * Cherry-picked later additions to the `master` branch: 222095d55ac8352fd08f8fa23869fcd58660cea8...92781cb4ce9f56bed3b3dea8f9000e33193b0512 ...

Here are the effective additions on top of `xalan-j_2_7_1_maint`:

-   https://github.com/apache/xalan-java/compare/xalan-j_2_7_1_maint...stanio:xalan-java:xalanj-2671-master-reset?w=1

**Comment by vlsi** [comment]
@stanio , thanks, I support resetting the master branch to your xalanj-2671-master-reset branch.

**Comment by jkesselm** [comment]
OK. Let's walk through this.

Clone (reverted) head. 

Confirm status:
```
[keshlam@goldtooth xalan-java]$ git log --oneline | head -n 10
92781cb4 Merge pull request #66 from mukulga/xalan-j_master_mukul
be0d250e committing minor changes to xalanj README file, as per the following change that was done earlier : movement of the 2.7.3_release test cases to jira directory. also making a minor improvement to error handling within xalanj implementation codebase, when variables were not been resolved within an xslt 1.0 stylesheet.
690bd044 Merge pull request #5 from jkesselm/master
6f418abf Revert default indent-amount
3a624b30 increasing the default indent amount for the xalanj document serializer. this makes it little bit easier to view xalanj xslt transformation result. doing this xalanj codebase change on 'master' branch. the previous commit, did this codebase change on xalanj branch xalan-j_xslt3.0.
3a51a5ad changing project name within .project file on the master branch
356ce496 updating master branch, to have same contents as the branch xalan-j_2_7_1_maint
0affa12b clearing all the project contents from the xalanj master branch
ff674397 Add SECURITY.md
222095d5 minor correction to XalanJ docs
```
Set up the "Master until 2023-10-17" tag.

Confirm that Git Blame erroneously shows Mukul as author.

Execute the master-reset.
```
keshlam@goldtooth xalan-java]$ git remote add stanio https://github.com/stanio/xalan-java.git
[keshlam@goldtooth xalan-java]$ git fetch --all
Fetching origin
Fetching stanio
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 25 (delta 14), reused 25 (delta 14), pack-reused 0
Unpacking objects: 100% (25/25), 2.87 KiB | 489.00 KiB/s, done.
From https://github.com/stanio/xalan-java
 * [new branch]        master     -> stanio/master
 * [new branch]        xalanj-2671-master-reset -> stanio/xalanj-2671-master-reset
 * [new branch]        xalanj-2671-restore-history -> stanio/xalanj-2671-restore-history
[keshlam@goldtooth xalan-java]$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
[keshlam@goldtooth xalan-java]$ git reset --hard stanio/xalanj-2671-master-reset
HEAD is now at 71a91c2d committing minor changes to xalanj README file, as per the following change that was done earlier : movement of the 2.7.3_release test cases to jira directory. also making a minor improvement to error handling within xalanj implementation codebase, when variables were not been resolved within an xslt 1.0 stylesheet.
```
Check blame: Looks good!

Check log:
```
[keshlam@goldtooth xalan-java]$ git log --oneline | head -n 10
71a91c2d committing minor changes to xalanj README file, as per the following change that was done earlier : movement of the 2.7.3_release test cases to jira directory. also making a minor improvement to error handling within xalanj implementation codebase, when variables were not been resolved within an xslt 1.0 stylesheet.
144e8667 Revert default indent-amount
5645f26b increasing the default indent amount for the xalanj document serializer. this makes it little bit easier to view xalanj xslt transformation result. doing this xalanj codebase change on 'master' branch. the previous commit, did this codebase change on xalanj branch xalan-j_xslt3.0.
6d440bf7 changing project name within .project file on the master branch
a055accd Add SECURITY.md
f51fdd9e resetting state of the branch, appropriate for git clone. deleting certain java files, that are generated by the tools during build.
25b9c336 minor corrections to, linux build.sh file
28169adb minor changes to, xalanj build configuration
49873086 minor changes to, xalanj readme file
8762a120 minor changes to, xalanj readme file
```
Merge hashes have changed; odd but OK.
Two commits seem to have vanished:
```
be0d250e committing minor changes to xalanj README file, as per the following change that was done earlier : movement of the 2.7.3_release test cases to jira directory. also making a minor improvement to error handling within xalanj implementation codebase, when variables were not been resolved within an xslt 1.0 stylesheet.
690bd044 Merge pull request #5 from jkesselm/master
```
But git diff says the only differences from head are:
    EOLs changed on LICENSE.txt, NOTICE.txt, createdb.sql, runDeby.bat, runXalan.bat, contact_us.xml
    about 75 files' Unix protection modes changed from 644 to 755 (execute bits set).
A bit of quick cli hackery fixed those; git diff now reports match.

Committed and forced push.   Log is now:
```
acdb8998 XALANJ-2671: Change history recovered. A bit of postprocessing was required to repair execute permissions and newlines.
71a91c2d committing minor changes to xalanj README file, as per the following change that was done earlier : movement of the 2.7.3_release test cases to jira directory. also making a minor improvement to error handling within xalanj implementation codebase, when variables were not been resolved within an xslt 1.0 stylesheet.
[etc]```

**Comment by stanio** [comment]
> Merge hashes have changed; odd but OK.

Not sure which merge hashes you're referring to but as I've pointed out in the PR description:

> * Two superfluous merge commits were dropped

I didn't do it intentionally but it is a consequence of the cherry-pick.

> Two commits seem to have vanished:
> 
> ```
> be0d250e committing minor changes to xalanj README file, as per the following change that was done earlier : movement of the 2.7.3_release test cases to jira directory. also making a minor improvement to error handling within xalanj implementation codebase, when variables were not been resolved within an xslt 1.0 stylesheet.
> 690bd044 Merge pull request #5 from jkesselm/master
> ```

As I've pointed out, the merge commit is gone, yes.  It has been unnecessary, anyway.  The first one you could see in your previous `git log` output – just with a different hash.  Again, this is a result of the cherry-pick.  The same commit applied to a different parent will have a different hash.

**Comment by stanio** [comment]
I suggest protecting the `master` branch from accidental force pushes, further.  The protection should be lifted only in such exceptional circumstances.

**Comment by jkesselm** [comment]
> I suggest protecting the `master` branch from accidental force pushes, further. The protection should be lifted only temporarily, in such exceptional circumstances.

Probably wise. Could you open a new Jira ticket on that, so we don't forget?

**Comment by jkesselm** [comment]
Oh, Great. 

It's been pointed out that my Maven fork (xalan-java-mvn) has the same missing history, and that merging it would risk losing that history. 

Flailing about trying to fix that...

**Pull request merged**
