### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by vlsi**
Code changes should be tested, so there should be CI for that

### CODE REVIEW

**Comment by jkesselm** [comment]
Haven't used Git's actions, but this looks reasonable to me.

**Comment by vlsi** [comment]
@jkesselm , care to merge?

**Comment by vlsi** [comment]
Apparently, this PR and the others were reverted as you performed “reset master branch”

You should have reset the master branch before merging the PRs.

What is your plan now?

**Comment by stanio** [comment]
> Apparently, this PR and the others were reverted as you performed “reset master branch”

This one has targeted and is currently in `xalan-j_2_7_1_maint`:

-   https://github.com/apache/xalan-java/commits/xalan-j_2_7_1_maint

I don't know if it is the right target but it hasn't been reverted and has nothing to do with the reset of the `master` branch.

**Comment by vlsi** [comment]
> I don't know if it is the right target but it hasn't been reverted and has nothing to do with the reset of the master branch.

Indeed, my bad then. Sorry for that.

I assumed the mainline would be the master branch, I saw the merge notifications yet the changes are not present on the master branch, that is why I assumed the recently merged changes were just lost.

In any case, the changes should be transplanted to the master branch and/or the master branch itself should be reset again to the updated 271 branch.

**Comment by stanio** [comment]
Current `xalan-j_2_7_1_maint` could be merged (via a merge commit) into `master`.

**Comment by vlsi** [comment]
Frankly speaking, I would suggest going with linear history instead of the merge commits which make xslt3 branch history much harder to read

**Comment by stanio** [comment]
I also would like not to see merge commits for single commit PRs but they are already a fact:

-   https://github.com/apache/xalan-java/commits/xalan-j_2_7_1_maint

Merges for syncing branches are admissible and most often necessary, in my opinion.

**Comment by jkesselm** [comment]
Or we can resubmit the change, making the PR against Master, Not sure if that's really any cleaner than the merge.

There is a presumption that patches to older versions (on the _maint branches) will be copied up to master/main, if they're still applicable. Since most patches are likely to be single commits, I think we just have to accept that this is sometimes going to happen. Readable history is a good thing, but that's legitimate history.

**Comment by jkesselm** [comment]
I've changed the yaml file to invoke the set of tests we normally run for regression testing, minus conf.xsltc which is not currently compatible with the automation (since it doesn't mute the longstanding known issues as we do in the main conformance tests). I also had to change where xalan-test lived at least for the duration of the fulldist build. 

So CI should now be running on the maint branch, and it should be safe to replicate/pull it over to master.

**Pull request merged**
