### PR TITLE
Replace local Brazil binary by Maven Central dependency

### PR DESCRIPTION
**Pull request by kriegaex**
Yesterday, I forked https://github.com/mbooth101/brazil (unavailable on Maven Central) to https://github.com/dev-aspectj/brazil, updated the POM and published a version under a group ID (`dev.aspectj`) I control. This commit uses that artifact (`dev.aspectj:sunlabs.brazil:2.3.1`), getting rid of the previously committed JAR and eliminating the need for a system-scoped dependency.

I verified that sample class `TransformHandler` still works as described with the new Brazil version and also updated the sample's read-me file.

@kubycsolutions, please review.

### CODE REVIEW

**Review by jkesselm — COMMENTED** [review]
Ah-HAH. Thank you, Alex; my attempts to find a version of Brazil we could reference kept getting lost somewhere in the Bermuda Triangle. Part of the point of this migration was to avoid carrying binaries in the Xalan package; nice to get this gap closed.

**Comment by kriegaex** [comment]
Welcome. I had noticed the warning about the system-scoped dependency during the build and also found your to-do comment. So I thought, I could fix that before I forget about it.

BTW, I much prefer Xander (or Alexander). I am not an Alex. Too many Alexes in this world already. 😂😉

**Comment by kubycsolutions** [comment]
Xander it is. Sorry, should have asked.

--
   /_  Joe Kesselman (he/him/his)
-/ _) My Alexa skill for New Music/New Sounds fans:
   /   https://www.amazon.com/dp/B09WJ3H657/

Caveat: Opinionated old geezer with overcompensated writer's block. May be redundant, verbose, prolix, sesquipedalian, didactic, officious, or redundant.
________________________________

**Comment by kriegaex** [comment]
Force-pushed Brazil read-me update, now explicitly explaining how to test right from the project's root directory.

**Pull request merged**
